"""Word hints shown when hovering a word in an exercise sentence (Duolingo's "hover hints").

Keys are lowercase words or short phrases; values are the meanings shown in the popover,
most likely meaning first. Phrases are matched before single words, so "buenos días"
reads as "good morning" instead of "good days". Names (Ana, Juan) have no hints, like
on Duolingo.
"""

# Spanish -> English
ES: dict[str, list[str]] = {
    # phrases
    "buenos días": ["good morning"],
    "buenas noches": ["good night", "good evening"],
    "por favor": ["please"],
    "muchas gracias": ["thank you very much", "thanks a lot"],
    "me gusta": ["I like"],
    "cómo estás": ["how are you"],
    "dónde está": ["where is"],
    # words
    "abuela": ["grandmother", "grandma"],
    "abuelo": ["grandfather", "grandpa"],
    "adiós": ["goodbye", "bye"],
    "agua": ["water"],
    "alta": ["tall", "high"],
    "amarillo": ["yellow"],
    "amigo": ["friend"],
    "arroz": ["rice"],
    "azul": ["blue"],
    "años": ["years", "years old"],
    "bebe": ["drinks", "(he/she) drinks", "is drinking"],
    "bebes": ["drink", "(you) drink"],
    "blanca": ["white"],
    "buenas": ["good"],
    "bueno": ["good", "well"],
    "buenos": ["good"],
    "café": ["coffee", "café"],
    "carne": ["meat", "beef"],
    "casa": ["house", "home"],
    "cielo": ["sky", "heaven"],
    "cinco": ["five"],
    "come": ["eats", "(he/she) eats", "is eating"],
    "comemos": ["eat", "(we) eat"],
    "como": ["eat", "(I) eat"],
    "cómo": ["how"],
    "cuatro": ["four"],
    "cuenta": ["check", "bill", "account"],
    "días": ["days", "morning (in 'buenos días')"],
    "doctora": ["doctor"],
    "dónde": ["where"],
    "dos": ["two"],
    "dulce": ["sweet", "candy"],
    "el": ["the"],
    "él": ["he", "him"],
    "ella": ["she", "her"],
    "ensalada": ["salad"],
    "eres": ["are", "(you) are"],
    "es": ["is", "(he/she/it) is"],
    "está": ["is", "(it) is"],
    "estás": ["are", "(you) are"],
    "favor": ["favor"],
    "fresco": ["fresh", "cool"],
    "frío": ["cold"],
    "galleta": ["cookie", "biscuit"],
    "galletas": ["cookies", "biscuits"],
    "gato": ["cat"],
    "gracias": ["thanks", "thank you"],
    "grande": ["big", "large"],
    "gusta": ["likes", "(it) pleases"],
    "hay": ["there is", "there are"],
    "helado": ["ice cream"],
    "hermana": ["sister"],
    "hermano": ["brother"],
    "hola": ["hello", "hi"],
    "hombre": ["man"],
    "jugo": ["juice"],
    "la": ["the"],
    "leche": ["milk"],
    "libro": ["book"],
    "madre": ["mother"],
    "maleta": ["suitcase"],
    "mamá": ["mom", "mother"],
    "manzana": ["apple"],
    "manzanas": ["apples"],
    "me": ["me", "(to) me"],
    "menú": ["menu"],
    "mi": ["my"],
    "muchas": ["many", "a lot of"],
    "mujer": ["woman", "wife"],
    "negro": ["black"],
    "niña": ["girl", "child"],
    "niño": ["boy", "child"],
    "niños": ["children", "kids", "boys"],
    "noches": ["nights"],
    "nosotros": ["we", "us"],
    "padre": ["father", "dad"],
    "pájaro": ["bird"],
    "pan": ["bread"],
    "pastel": ["cake", "pie"],
    "pequeño": ["small", "little"],
    "perro": ["dog"],
    "perros": ["dogs"],
    "pescado": ["fish"],
    "por": ["for", "by"],
    "queremos": ["want", "(we) want"],
    "quiero": ["want", "(I) want"],
    "roja": ["red"],
    "seis": ["six"],
    "señor": ["sir", "mister", "Mr."],
    "sí": ["yes"],
    "sopa": ["soup"],
    "soy": ["am", "(I) am"],
    "té": ["tea"],
    "tengo": ["have", "(I) have"],
    "tés": ["teas"],
    "tiene": ["has", "(he/she) has"],
    "tienes": ["have", "(you) have"],
    "tres": ["three"],
    "tú": ["you"],
    "un": ["a", "an", "one"],
    "una": ["a", "an", "one"],
    "vaca": ["cow"],
    "verde": ["green"],
    "y": ["and"],
    "yo": ["I"],
}

# English -> Spanish (for sentences the learner translates into Spanish)
EN: dict[str, list[str]] = {
    # phrases
    "good morning": ["buenos días"],
    "thank you": ["gracias"],
    "there are": ["hay"],
    "do you have": ["¿tienes?"],
    "i have": ["tengo"],
    "i want": ["quiero"],
    "i eat": ["como"],
    "i like": ["me gusta"],
    "we want": ["queremos"],
    # words
    "a": ["un", "una"],
    "an": ["un", "una"],
    "and": ["y"],
    "apple": ["manzana"],
    "are": ["son", "están"],
    "big": ["grande"],
    "bird": ["pájaro"],
    "blue": ["azul"],
    "book": ["libro"],
    "boy": ["niño", "chico"],
    "bread": ["pan"],
    "brother": ["hermano"],
    "cake": ["pastel"],
    "cat": ["gato"],
    "check": ["cuenta"],
    "cheese": ["queso"],
    "children": ["niños"],
    "coffee": ["café"],
    "cookie": ["galleta"],
    "cookies": ["galletas"],
    "cow": ["vaca"],
    "dad": ["papá"],
    "dog": ["perro"],
    "drinks": ["bebe", "toma"],
    "eat": ["comer", "como"],
    "eats": ["come"],
    "father": ["padre", "papá"],
    "fish": ["pescado", "pez"],
    "five": ["cinco"],
    "four": ["cuatro"],
    "fresh": ["fresco"],
    "friend": ["amigo", "amiga"],
    "girl": ["niña", "chica"],
    "good": ["bueno", "buena"],
    "goodbye": ["adiós"],
    "grandmother": ["abuela"],
    "green": ["verde"],
    "have": ["tener", "tengo"],
    "he": ["él"],
    "horse": ["caballo"],
    "house": ["casa"],
    "i": ["yo"],
    "is": ["es", "está"],
    "juice": ["jugo"],
    "like": ["gustar"],
    "meat": ["carne"],
    "milk": ["leche"],
    "morning": ["mañana"],
    "mouse": ["ratón"],
    "my": ["mi"],
    "one": ["un", "uno", "una"],
    "please": ["por favor"],
    "salad": ["ensalada"],
    "sandwich": ["sándwich"],
    "she": ["ella"],
    "sir": ["señor"],
    "sister": ["hermana"],
    "six": ["seis"],
    "sky": ["cielo"],
    "small": ["pequeño"],
    "suitcase": ["maleta"],
    "sweet": ["dulce"],
    "tall": ["alto", "alta"],
    "teas": ["tés"],
    "the": ["el", "la"],
    "two": ["dos"],
    "want": ["querer", "quiero"],
    "water": ["agua"],
    "we": ["nosotros"],
    "white": ["blanco", "blanca"],
    "woman": ["mujer"],
    "yellow": ["amarillo"],
    "yes": ["sí"],
    "you": ["tú"],
}

HINTS: dict[str, dict[str, list[str]]] = {"es": ES, "en": EN}
