"""Word hints shown when hovering a word in an exercise sentence (Duolingo's "hover hints").

Like Duolingo, a hint gives the meaning the word has in the lesson sentences, followed by
an example sentence showing the word in use (with its translation). Keys are lowercase
words or short phrases. Phrases are matched before single words, so "buenos días" reads
as "good morning" rather than "good days". Names (Ana, Juan) have no hints, as on Duolingo.

Each entry is (meanings, example sentence, example translation). Examples are always in
Spanish, the language being learned, so English words show the Spanish word in a sentence.
"""

Hint = tuple[list[str], str, str]

# Spanish -> English
ES: dict[str, Hint] = {
    # phrases
    "buenos días": (["good morning"], "Buenos días, señor.", "Good morning, sir."),
    "buenas noches": (["good night", "good evening"], "Buenas noches, papá.", "Good night, dad."),
    "por favor": (["please"], "Agua, por favor.", "Water, please."),
    "muchas gracias": (["thank you very much"], "Muchas gracias, Ana.", "Thank you very much, Ana."),
    "me gusta": (["I like"], "Me gusta el café.", "I like coffee."),
    "cómo estás": (["how are you"], "Hola, Juan, ¿cómo estás?", "Hi, Juan, how are you?"),
    "dónde está": (["where is"], "¿Dónde está mi libro?", "Where is my book?"),
    # words
    "abuela": (["grandmother", "grandma"], "Mi abuela bebe té.", "My grandmother drinks tea."),
    "abuelo": (["grandfather", "grandpa"], "El abuelo come pan.", "Grandpa eats bread."),
    "adiós": (["goodbye", "bye"], "Adiós, mamá.", "Goodbye, mom."),
    "agua": (["water"], "Yo bebo agua.", "I drink water."),
    "alta": (["tall"], "La mujer es alta.", "The woman is tall."),
    "amarillo": (["yellow"], "El libro es amarillo.", "The book is yellow."),
    "amigo": (["friend"], "Juan es mi amigo.", "Juan is my friend."),
    "arroz": (["rice"], "Ella come arroz.", "She eats rice."),
    "azul": (["blue"], "Mi casa es azul.", "My house is blue."),
    "años": (["years (old)"], "Ana tiene cinco años.", "Ana is five years old."),
    "bebe": (["drinks", "is drinking"], "El gato bebe agua.", "The cat drinks water."),
    "bebes": (["(you) drink"], "¿Tú bebes café?", "Do you drink coffee?"),
    "blanca": (["white"], "La leche es blanca.", "The milk is white."),
    "buenas": (["good"], "Buenas noches, Ana.", "Good night, Ana."),
    "bueno": (["good"], "El pan es bueno.", "The bread is good."),
    "buenos": (["good"], "Buenos días, papá.", "Good morning, dad."),
    "café": (["coffee"], "Quiero un café.", "I want a coffee."),
    "carne": (["meat"], "El perro come carne.", "The dog eats meat."),
    "casa": (["house", "home"], "Mi casa es grande.", "My house is big."),
    "cielo": (["sky"], "El cielo es azul.", "The sky is blue."),
    "cinco": (["five"], "Tengo cinco libros.", "I have five books."),
    "come": (["eats", "is eating"], "Mi hermano come pan.", "My brother eats bread."),
    "comemos": (["(we) eat"], "Nosotros comemos pan.", "We eat bread."),
    "como": (["(I) eat"], "Yo como arroz.", "I eat rice."),
    "cómo": (["how"], "¿Cómo estás, Ana?", "How are you, Ana?"),
    "cuatro": (["four"], "Hay cuatro gatos.", "There are four cats."),
    "cuenta": (["check", "bill"], "La cuenta, por favor.", "The check, please."),
    "días": (["days", "morning (buenos días)"], "Buenos días, Juan.", "Good morning, Juan."),
    "doctora": (["doctor"], "Ana es doctora.", "Ana is a doctor."),
    "dónde": (["where"], "¿Dónde está el gato?", "Where is the cat?"),
    "dos": (["two"], "Tengo dos perros.", "I have two dogs."),
    "dulce": (["sweet"], "La manzana es dulce.", "The apple is sweet."),
    "el": (["the"], "El perro es negro.", "The dog is black."),
    "él": (["he"], "Él es mi hermano.", "He is my brother."),
    "ella": (["she"], "Ella es mi amiga.", "She is my friend."),
    "ensalada": (["salad"], "Quiero una ensalada.", "I want a salad."),
    "eres": (["(you) are"], "Tú eres mi amigo.", "You are my friend."),
    "es": (["is"], "Mi gato es pequeño.", "My cat is small."),
    "está": (["is"], "¿Dónde está Ana?", "Where is Ana?"),
    "estás": (["(you) are"], "¿Cómo estás, mamá?", "How are you, mom?"),
    "favor": (["favor"], "Un té, por favor.", "A tea, please."),
    "fresco": (["fresh"], "El pan es fresco.", "The bread is fresh."),
    "frío": (["cold"], "El jugo es frío.", "The juice is cold."),
    "galleta": (["cookie"], "El niño come una galleta.", "The boy eats a cookie."),
    "galletas": (["cookies"], "Tengo dos galletas.", "I have two cookies."),
    "gato": (["cat"], "El gato bebe leche.", "The cat drinks milk."),
    "gracias": (["thank you", "thanks"], "Gracias, mamá.", "Thank you, mom."),
    "grande": (["big"], "El perro es grande.", "The dog is big."),
    "gusta": (["like (me gusta)"], "Me gusta el pan.", "I like bread."),
    "hay": (["there is", "there are"], "Hay dos gatos.", "There are two cats."),
    "helado": (["ice cream"], "Quiero un helado.", "I want an ice cream."),
    "hermana": (["sister"], "Mi hermana come pan.", "My sister eats bread."),
    "hermano": (["brother"], "Él es mi hermano.", "He is my brother."),
    "hola": (["hello", "hi"], "Hola, Juan.", "Hello, Juan."),
    "hombre": (["man"], "El hombre bebe café.", "The man drinks coffee."),
    "jugo": (["juice"], "Ella bebe jugo.", "She drinks juice."),
    "la": (["the"], "La niña come pan.", "The girl eats bread."),
    "leche": (["milk"], "Yo bebo leche.", "I drink milk."),
    "libro": (["book"], "Tengo un libro.", "I have a book."),
    "madre": (["mother"], "Mi madre es alta.", "My mother is tall."),
    "maleta": (["suitcase"], "La maleta es grande.", "The suitcase is big."),
    "mamá": (["mom"], "Hola, mamá.", "Hi, mom."),
    "manzana": (["apple"], "La manzana es roja.", "The apple is red."),
    "manzanas": (["apples"], "Hay tres manzanas.", "There are three apples."),
    "me": (["me", "(to) me"], "Me gusta la sopa.", "I like the soup."),
    "menú": (["menu"], "El menú, por favor.", "The menu, please."),
    "mi": (["my"], "Mi perro es pequeño.", "My dog is small."),
    "muchas": (["many", "a lot of"], "Muchas gracias, señor.", "Thank you very much, sir."),
    "mujer": (["woman"], "La mujer come pan.", "The woman eats bread."),
    "negro": (["black"], "Mi perro es negro.", "My dog is black."),
    "niña": (["girl"], "La niña es pequeña.", "The girl is small."),
    "niño": (["boy"], "El niño bebe leche.", "The boy drinks milk."),
    "niños": (["children", "boys"], "Los niños comen pan.", "The children eat bread."),
    "noches": (["nights", "night (buenas noches)"], "Buenas noches, Juan.", "Good night, Juan."),
    "nosotros": (["we"], "Nosotros bebemos agua.", "We drink water."),
    "padre": (["father"], "Mi padre come carne.", "My father eats meat."),
    "pájaro": (["bird"], "El pájaro es azul.", "The bird is blue."),
    "pan": (["bread"], "Yo como pan.", "I eat bread."),
    "pastel": (["cake"], "El pastel es grande.", "The cake is big."),
    "pequeño": (["small", "little"], "El gato es pequeño.", "The cat is small."),
    "perro": (["dog"], "Mi perro come carne.", "My dog eats meat."),
    "perros": (["dogs"], "Hay dos perros.", "There are two dogs."),
    "pescado": (["fish"], "Yo como pescado.", "I eat fish."),
    "por": (["for", "by"], "Agua, por favor.", "Water, please."),
    "queremos": (["(we) want"], "Queremos dos cafés.", "We want two coffees."),
    "quiero": (["(I) want"], "Quiero agua.", "I want water."),
    "roja": (["red"], "La casa es roja.", "The house is red."),
    "seis": (["six"], "Tengo seis libros.", "I have six books."),
    "señor": (["sir", "Mr."], "Gracias, señor.", "Thank you, sir."),
    "sí": (["yes"], "Sí, gracias.", "Yes, thank you."),
    "sopa": (["soup"], "Quiero una sopa.", "I want a soup."),
    "soy": (["(I) am"], "Yo soy Ana.", "I am Ana."),
    "té": (["tea"], "Mi abuela bebe té.", "My grandmother drinks tea."),
    "tengo": (["(I) have"], "Tengo un gato.", "I have a cat."),
    "tés": (["teas"], "Dos tés, por favor.", "Two teas, please."),
    "tiene": (["has"], "Ana tiene un perro.", "Ana has a dog."),
    "tienes": (["(you) have"], "¿Tienes un libro?", "Do you have a book?"),
    "tres": (["three"], "Tengo tres gatos.", "I have three cats."),
    "tú": (["you"], "Tú eres alta.", "You are tall."),
    "un": (["a", "an"], "Tengo un perro.", "I have a dog."),
    "una": (["a", "an"], "Quiero una manzana.", "I want an apple."),
    "vaca": (["cow"], "La vaca bebe agua.", "The cow drinks water."),
    "verde": (["green"], "La manzana es verde.", "The apple is green."),
    "y": (["and"], "Pan y agua, por favor.", "Bread and water, please."),
    "yo": (["I"], "Yo bebo leche.", "I drink milk."),
}

# English -> Spanish (sentences the learner translates into Spanish)
EN: dict[str, Hint] = {
    # phrases
    "good morning": (["buenos días"], "Buenos días, mamá.", "Good morning, mom."),
    "thank you": (["gracias"], "Gracias, Juan.", "Thank you, Juan."),
    "there are": (["hay"], "Hay tres perros.", "There are three dogs."),
    "do you have": (["¿tienes?"], "¿Tienes agua?", "Do you have water?"),
    "i have": (["tengo"], "Tengo un libro.", "I have a book."),
    "i want": (["quiero"], "Quiero pan.", "I want bread."),
    "i eat": (["como"], "Yo como arroz.", "I eat rice."),
    "i like": (["me gusta"], "Me gusta el té.", "I like tea."),
    "we want": (["queremos"], "Queremos agua.", "We want water."),
    # words
    "a": (["un", "una"], "Tengo un gato.", "I have a cat."),
    "an": (["una", "un"], "Quiero una manzana.", "I want an apple."),
    "and": (["y"], "Café y leche.", "Coffee and milk."),
    "apple": (["manzana"], "La manzana es roja.", "The apple is red."),
    "big": (["grande"], "La casa es grande.", "The house is big."),
    "bird": (["pájaro"], "El pájaro es azul.", "The bird is blue."),
    "blue": (["azul"], "Mi libro es azul.", "My book is blue."),
    "book": (["libro"], "El libro es verde.", "The book is green."),
    "boy": (["niño"], "El niño come pan.", "The boy eats bread."),
    "bread": (["pan"], "Yo como pan.", "I eat bread."),
    "brother": (["hermano"], "Mi hermano es alto.", "My brother is tall."),
    "cake": (["pastel"], "Quiero un pastel.", "I want a cake."),
    "cat": (["gato"], "El gato es negro.", "The cat is black."),
    "check": (["cuenta"], "La cuenta, por favor.", "The check, please."),
    "cheese": (["queso"], "Me gusta el queso.", "I like cheese."),
    "children": (["niños"], "Los niños beben leche.", "The children drink milk."),
    "coffee": (["café"], "Un café, por favor.", "A coffee, please."),
    "cookie": (["galleta"], "Ana come una galleta.", "Ana eats a cookie."),
    "cookies": (["galletas"], "Quiero dos galletas.", "I want two cookies."),
    "cow": (["vaca"], "La vaca es negra.", "The cow is black."),
    "dad": (["papá"], "Hola, papá.", "Hi, dad."),
    "dog": (["perro"], "Tengo un perro.", "I have a dog."),
    "drinks": (["bebe"], "Juan bebe agua.", "Juan drinks water."),
    "eat": (["como", "comemos"], "Nosotros comemos pan.", "We eat bread."),
    "eats": (["come"], "El gato come pescado.", "The cat eats fish."),
    "father": (["padre"], "Mi padre bebe café.", "My father drinks coffee."),
    "fish": (["pescado"], "El pescado es bueno.", "The fish is good."),
    "five": (["cinco"], "Hay cinco gatos.", "There are five cats."),
    "four": (["cuatro"], "Tengo cuatro libros.", "I have four books."),
    "fresh": (["fresco"], "El pan es fresco.", "The bread is fresh."),
    "friend": (["amigo", "amiga"], "Él es mi amigo.", "He is my friend."),
    "girl": (["niña"], "La niña bebe leche.", "The girl drinks milk."),
    "good": (["bueno", "buena"], "El café es bueno.", "The coffee is good."),
    "goodbye": (["adiós"], "Adiós, Ana.", "Goodbye, Ana."),
    "grandmother": (["abuela"], "Mi abuela es alta.", "My grandmother is tall."),
    "green": (["verde"], "La casa es verde.", "The house is green."),
    "have": (["tengo", "tienes"], "Tengo dos gatos.", "I have two cats."),
    "he": (["él"], "Él come pan.", "He eats bread."),
    "horse": (["caballo"], "El caballo es grande.", "The horse is big."),
    "house": (["casa"], "Mi casa es pequeña.", "My house is small."),
    "i": (["yo"], "Yo bebo agua.", "I drink water."),
    "is": (["es"], "El gato es pequeño.", "The cat is small."),
    "juice": (["jugo"], "Quiero un jugo.", "I want a juice."),
    "like": (["gusta (me gusta)"], "Me gusta la leche.", "I like milk."),
    "meat": (["carne"], "El perro come carne.", "The dog eats meat."),
    "milk": (["leche"], "Ella bebe leche.", "She drinks milk."),
    "morning": (["días (buenos días)", "mañana"], "Buenos días, Ana.", "Good morning, Ana."),
    "mouse": (["ratón"], "El ratón es pequeño.", "The mouse is small."),
    "my": (["mi"], "Mi gato es negro.", "My cat is black."),
    "one": (["un", "una"], "Un café, por favor.", "One coffee, please."),
    "please": (["por favor"], "Agua, por favor.", "Water, please."),
    "salad": (["ensalada"], "La ensalada es buena.", "The salad is good."),
    "sandwich": (["sándwich"], "Quiero un sándwich.", "I want a sandwich."),
    "she": (["ella"], "Ella bebe café.", "She drinks coffee."),
    "sir": (["señor"], "Hola, señor.", "Hello, sir."),
    "sister": (["hermana"], "Mi hermana es doctora.", "My sister is a doctor."),
    "six": (["seis"], "Hay seis manzanas.", "There are six apples."),
    "sky": (["cielo"], "El cielo es azul.", "The sky is blue."),
    "small": (["pequeño", "pequeña"], "Mi casa es pequeña.", "My house is small."),
    "suitcase": (["maleta"], "Mi maleta es azul.", "My suitcase is blue."),
    "sweet": (["dulce"], "El pastel es dulce.", "The cake is sweet."),
    "tall": (["alta", "alto"], "Mi hermana es alta.", "My sister is tall."),
    "teas": (["tés"], "Dos tés, por favor.", "Two teas, please."),
    "the": (["el", "la"], "El niño come pan.", "The boy eats bread."),
    "two": (["dos"], "Tengo dos perros.", "I have two dogs."),
    "want": (["quiero", "queremos"], "Quiero una sopa.", "I want a soup."),
    "water": (["agua"], "Quiero agua.", "I want water."),
    "we": (["nosotros"], "Nosotros comemos arroz.", "We eat rice."),
    "white": (["blanca", "blanco"], "La casa es blanca.", "The house is white."),
    "woman": (["mujer"], "La mujer bebe té.", "The woman drinks tea."),
    "yellow": (["amarillo"], "El pájaro es amarillo.", "The bird is yellow."),
    "yes": (["sí"], "Sí, gracias.", "Yes, thank you."),
    "you": (["tú"], "Tú eres mi amigo.", "You are my friend."),
}

HINTS: dict[str, dict[str, Hint]] = {"es": ES, "en": EN}
